// Code generated by entproto. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: entpb/entpb.proto

package entpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBranchRequest_View int32

const (
	GetBranchRequest_VIEW_UNSPECIFIED GetBranchRequest_View = 0
	GetBranchRequest_BASIC            GetBranchRequest_View = 1
	GetBranchRequest_WITH_EDGE_IDS    GetBranchRequest_View = 2
)

// Enum value maps for GetBranchRequest_View.
var (
	GetBranchRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetBranchRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetBranchRequest_View) Enum() *GetBranchRequest_View {
	p := new(GetBranchRequest_View)
	*p = x
	return p
}

func (x GetBranchRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetBranchRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[0].Descriptor()
}

func (GetBranchRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[0]
}

func (x GetBranchRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetBranchRequest_View.Descriptor instead.
func (GetBranchRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{2, 0}
}

type ListBranchRequest_View int32

const (
	ListBranchRequest_VIEW_UNSPECIFIED ListBranchRequest_View = 0
	ListBranchRequest_BASIC            ListBranchRequest_View = 1
	ListBranchRequest_WITH_EDGE_IDS    ListBranchRequest_View = 2
)

// Enum value maps for ListBranchRequest_View.
var (
	ListBranchRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListBranchRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListBranchRequest_View) Enum() *ListBranchRequest_View {
	p := new(ListBranchRequest_View)
	*p = x
	return p
}

func (x ListBranchRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListBranchRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[1].Descriptor()
}

func (ListBranchRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[1]
}

func (x ListBranchRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListBranchRequest_View.Descriptor instead.
func (ListBranchRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{5, 0}
}

type GetCompanyRequest_View int32

const (
	GetCompanyRequest_VIEW_UNSPECIFIED GetCompanyRequest_View = 0
	GetCompanyRequest_BASIC            GetCompanyRequest_View = 1
	GetCompanyRequest_WITH_EDGE_IDS    GetCompanyRequest_View = 2
)

// Enum value maps for GetCompanyRequest_View.
var (
	GetCompanyRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetCompanyRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetCompanyRequest_View) Enum() *GetCompanyRequest_View {
	p := new(GetCompanyRequest_View)
	*p = x
	return p
}

func (x GetCompanyRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetCompanyRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[2].Descriptor()
}

func (GetCompanyRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[2]
}

func (x GetCompanyRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetCompanyRequest_View.Descriptor instead.
func (GetCompanyRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{11, 0}
}

type ListCompanyRequest_View int32

const (
	ListCompanyRequest_VIEW_UNSPECIFIED ListCompanyRequest_View = 0
	ListCompanyRequest_BASIC            ListCompanyRequest_View = 1
	ListCompanyRequest_WITH_EDGE_IDS    ListCompanyRequest_View = 2
)

// Enum value maps for ListCompanyRequest_View.
var (
	ListCompanyRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListCompanyRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListCompanyRequest_View) Enum() *ListCompanyRequest_View {
	p := new(ListCompanyRequest_View)
	*p = x
	return p
}

func (x ListCompanyRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListCompanyRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[3].Descriptor()
}

func (ListCompanyRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[3]
}

func (x ListCompanyRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListCompanyRequest_View.Descriptor instead.
func (ListCompanyRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{14, 0}
}

type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	ContactInfo   string                 `protobuf:"bytes,5,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Company       *Company               `protobuf:"bytes,8,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_entpb_entpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{0}
}

func (x *Branch) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Branch) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Branch) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

func (x *Branch) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Branch) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Branch) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

type CreateBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchRequest) Reset() {
	*x = CreateBranchRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchRequest) ProtoMessage() {}

func (x *CreateBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchRequest.ProtoReflect.Descriptor instead.
func (*CreateBranchRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBranchRequest) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

type GetBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetBranchRequest_View  `protobuf:"varint,2,opt,name=view,proto3,enum=entpb.GetBranchRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchRequest) Reset() {
	*x = GetBranchRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchRequest) ProtoMessage() {}

func (x *GetBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchRequest.ProtoReflect.Descriptor instead.
func (*GetBranchRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetBranchRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetBranchRequest) GetView() GetBranchRequest_View {
	if x != nil {
		return x.View
	}
	return GetBranchRequest_VIEW_UNSPECIFIED
}

type UpdateBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBranchRequest) Reset() {
	*x = UpdateBranchRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBranchRequest) ProtoMessage() {}

func (x *UpdateBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBranchRequest.ProtoReflect.Descriptor instead.
func (*UpdateBranchRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBranchRequest) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

type DeleteBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBranchRequest) Reset() {
	*x = DeleteBranchRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBranchRequest) ProtoMessage() {}

func (x *DeleteBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBranchRequest.ProtoReflect.Descriptor instead.
func (*DeleteBranchRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBranchRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type ListBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListBranchRequest_View `protobuf:"varint,3,opt,name=view,proto3,enum=entpb.ListBranchRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchRequest) Reset() {
	*x = ListBranchRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchRequest) ProtoMessage() {}

func (x *ListBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchRequest.ProtoReflect.Descriptor instead.
func (*ListBranchRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{5}
}

func (x *ListBranchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBranchRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListBranchRequest) GetView() ListBranchRequest_View {
	if x != nil {
		return x.View
	}
	return ListBranchRequest_VIEW_UNSPECIFIED
}

type ListBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchList    []*Branch              `protobuf:"bytes,1,rep,name=branch_list,json=branchList,proto3" json:"branch_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchResponse) Reset() {
	*x = ListBranchResponse{}
	mi := &file_entpb_entpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchResponse) ProtoMessage() {}

func (x *ListBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchResponse.ProtoReflect.Descriptor instead.
func (*ListBranchResponse) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{6}
}

func (x *ListBranchResponse) GetBranchList() []*Branch {
	if x != nil {
		return x.BranchList
	}
	return nil
}

func (x *ListBranchResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchCreateBranchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*CreateBranchRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateBranchesRequest) Reset() {
	*x = BatchCreateBranchesRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateBranchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateBranchesRequest) ProtoMessage() {}

func (x *BatchCreateBranchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateBranchesRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateBranchesRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{7}
}

func (x *BatchCreateBranchesRequest) GetRequests() []*CreateBranchRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateBranchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branches      []*Branch              `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateBranchesResponse) Reset() {
	*x = BatchCreateBranchesResponse{}
	mi := &file_entpb_entpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateBranchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateBranchesResponse) ProtoMessage() {}

func (x *BatchCreateBranchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateBranchesResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateBranchesResponse) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{8}
}

func (x *BatchCreateBranchesResponse) GetBranches() []*Branch {
	if x != nil {
		return x.Branches
	}
	return nil
}

type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Branches      []*Branch              `protobuf:"bytes,6,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_entpb_entpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{9}
}

func (x *Company) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Company) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Company) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Company) GetBranches() []*Branch {
	if x != nil {
		return x.Branches
	}
	return nil
}

type CreateCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       *Company               `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyRequest) Reset() {
	*x = CreateCompanyRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyRequest) ProtoMessage() {}

func (x *CreateCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyRequest.ProtoReflect.Descriptor instead.
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCompanyRequest) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

type GetCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetCompanyRequest_View `protobuf:"varint,2,opt,name=view,proto3,enum=entpb.GetCompanyRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyRequest) Reset() {
	*x = GetCompanyRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyRequest) ProtoMessage() {}

func (x *GetCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{11}
}

func (x *GetCompanyRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetCompanyRequest) GetView() GetCompanyRequest_View {
	if x != nil {
		return x.View
	}
	return GetCompanyRequest_VIEW_UNSPECIFIED
}

type UpdateCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       *Company               `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanyRequest) Reset() {
	*x = UpdateCompanyRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanyRequest) ProtoMessage() {}

func (x *UpdateCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanyRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompanyRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateCompanyRequest) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

type DeleteCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompanyRequest) Reset() {
	*x = DeleteCompanyRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompanyRequest) ProtoMessage() {}

func (x *DeleteCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompanyRequest.ProtoReflect.Descriptor instead.
func (*DeleteCompanyRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCompanyRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type ListCompanyRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	PageSize      int32                   `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                  `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListCompanyRequest_View `protobuf:"varint,3,opt,name=view,proto3,enum=entpb.ListCompanyRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompanyRequest) Reset() {
	*x = ListCompanyRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompanyRequest) ProtoMessage() {}

func (x *ListCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompanyRequest.ProtoReflect.Descriptor instead.
func (*ListCompanyRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{14}
}

func (x *ListCompanyRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCompanyRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCompanyRequest) GetView() ListCompanyRequest_View {
	if x != nil {
		return x.View
	}
	return ListCompanyRequest_VIEW_UNSPECIFIED
}

type ListCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyList   []*Company             `protobuf:"bytes,1,rep,name=company_list,json=companyList,proto3" json:"company_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompanyResponse) Reset() {
	*x = ListCompanyResponse{}
	mi := &file_entpb_entpb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompanyResponse) ProtoMessage() {}

func (x *ListCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompanyResponse.ProtoReflect.Descriptor instead.
func (*ListCompanyResponse) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{15}
}

func (x *ListCompanyResponse) GetCompanyList() []*Company {
	if x != nil {
		return x.CompanyList
	}
	return nil
}

func (x *ListCompanyResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchCreateCompaniesRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Requests      []*CreateCompanyRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateCompaniesRequest) Reset() {
	*x = BatchCreateCompaniesRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateCompaniesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateCompaniesRequest) ProtoMessage() {}

func (x *BatchCreateCompaniesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateCompaniesRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateCompaniesRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{16}
}

func (x *BatchCreateCompaniesRequest) GetRequests() []*CreateCompanyRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateCompaniesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Companies     []*Company             `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateCompaniesResponse) Reset() {
	*x = BatchCreateCompaniesResponse{}
	mi := &file_entpb_entpb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateCompaniesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateCompaniesResponse) ProtoMessage() {}

func (x *BatchCreateCompaniesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateCompaniesResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateCompaniesResponse) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{17}
}

func (x *BatchCreateCompaniesResponse) GetCompanies() []*Company {
	if x != nil {
		return x.Companies
	}
	return nil
}

var File_entpb_entpb_proto protoreflect.FileDescriptor

const file_entpb_entpb_proto_rawDesc = "" +
	"\n" +
	"\x11entpb/entpb.proto\x12\x05entpb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x02\n" +
	"\x06Branch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12!\n" +
	"\fcontact_info\x18\x05 \x01(\tR\vcontactInfo\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12(\n" +
	"\acompany\x18\b \x01(\v2\x0e.entpb.CompanyR\acompany\"<\n" +
	"\x13CreateBranchRequest\x12%\n" +
	"\x06branch\x18\x01 \x01(\v2\r.entpb.BranchR\x06branch\"\x90\x01\n" +
	"\x10GetBranchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x120\n" +
	"\x04view\x18\x02 \x01(\x0e2\x1c.entpb.GetBranchRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"<\n" +
	"\x13UpdateBranchRequest\x12%\n" +
	"\x06branch\x18\x01 \x01(\v2\r.entpb.BranchR\x06branch\"%\n" +
	"\x13DeleteBranchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\xbe\x01\n" +
	"\x11ListBranchRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x121\n" +
	"\x04view\x18\x03 \x01(\x0e2\x1d.entpb.ListBranchRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"l\n" +
	"\x12ListBranchResponse\x12.\n" +
	"\vbranch_list\x18\x01 \x03(\v2\r.entpb.BranchR\n" +
	"branchList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"T\n" +
	"\x1aBatchCreateBranchesRequest\x126\n" +
	"\brequests\x18\x01 \x03(\v2\x1a.entpb.CreateBranchRequestR\brequests\"H\n" +
	"\x1bBatchCreateBranchesResponse\x12)\n" +
	"\bbranches\x18\x01 \x03(\v2\r.entpb.BranchR\bbranches\"\xe8\x01\n" +
	"\aCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12)\n" +
	"\bbranches\x18\x06 \x03(\v2\r.entpb.BranchR\bbranches\"@\n" +
	"\x14CreateCompanyRequest\x12(\n" +
	"\acompany\x18\x01 \x01(\v2\x0e.entpb.CompanyR\acompany\"\x92\x01\n" +
	"\x11GetCompanyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x121\n" +
	"\x04view\x18\x02 \x01(\x0e2\x1d.entpb.GetCompanyRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"@\n" +
	"\x14UpdateCompanyRequest\x12(\n" +
	"\acompany\x18\x01 \x01(\v2\x0e.entpb.CompanyR\acompany\"&\n" +
	"\x14DeleteCompanyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\xc0\x01\n" +
	"\x12ListCompanyRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x122\n" +
	"\x04view\x18\x03 \x01(\x0e2\x1e.entpb.ListCompanyRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"p\n" +
	"\x13ListCompanyResponse\x121\n" +
	"\fcompany_list\x18\x01 \x03(\v2\x0e.entpb.CompanyR\vcompanyList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"V\n" +
	"\x1bBatchCreateCompaniesRequest\x127\n" +
	"\brequests\x18\x01 \x03(\v2\x1b.entpb.CreateCompanyRequestR\brequests\"L\n" +
	"\x1cBatchCreateCompaniesResponse\x12,\n" +
	"\tcompanies\x18\x01 \x03(\v2\x0e.entpb.CompanyR\tcompanies2\xf9\x02\n" +
	"\rBranchService\x123\n" +
	"\x06Create\x12\x1a.entpb.CreateBranchRequest\x1a\r.entpb.Branch\x12-\n" +
	"\x03Get\x12\x17.entpb.GetBranchRequest\x1a\r.entpb.Branch\x123\n" +
	"\x06Update\x12\x1a.entpb.UpdateBranchRequest\x1a\r.entpb.Branch\x12<\n" +
	"\x06Delete\x12\x1a.entpb.DeleteBranchRequest\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x04List\x12\x18.entpb.ListBranchRequest\x1a\x19.entpb.ListBranchResponse\x12T\n" +
	"\vBatchCreate\x12!.entpb.BatchCreateBranchesRequest\x1a\".entpb.BatchCreateBranchesResponse2\x85\x03\n" +
	"\x0eCompanyService\x125\n" +
	"\x06Create\x12\x1b.entpb.CreateCompanyRequest\x1a\x0e.entpb.Company\x12/\n" +
	"\x03Get\x12\x18.entpb.GetCompanyRequest\x1a\x0e.entpb.Company\x125\n" +
	"\x06Update\x12\x1b.entpb.UpdateCompanyRequest\x1a\x0e.entpb.Company\x12=\n" +
	"\x06Delete\x12\x1b.entpb.DeleteCompanyRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\x04List\x12\x19.entpb.ListCompanyRequest\x1a\x1a.entpb.ListCompanyResponse\x12V\n" +
	"\vBatchCreate\x12\".entpb.BatchCreateCompaniesRequest\x1a#.entpb.BatchCreateCompaniesResponseB:Z8github.com/huynhthanhthao/hrm_hr_service/ent/proto/entpbb\x06proto3"

var (
	file_entpb_entpb_proto_rawDescOnce sync.Once
	file_entpb_entpb_proto_rawDescData []byte
)

func file_entpb_entpb_proto_rawDescGZIP() []byte {
	file_entpb_entpb_proto_rawDescOnce.Do(func() {
		file_entpb_entpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entpb_entpb_proto_rawDesc), len(file_entpb_entpb_proto_rawDesc)))
	})
	return file_entpb_entpb_proto_rawDescData
}

var file_entpb_entpb_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_entpb_entpb_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_entpb_entpb_proto_goTypes = []any{
	(GetBranchRequest_View)(0),           // 0: entpb.GetBranchRequest.View
	(ListBranchRequest_View)(0),          // 1: entpb.ListBranchRequest.View
	(GetCompanyRequest_View)(0),          // 2: entpb.GetCompanyRequest.View
	(ListCompanyRequest_View)(0),         // 3: entpb.ListCompanyRequest.View
	(*Branch)(nil),                       // 4: entpb.Branch
	(*CreateBranchRequest)(nil),          // 5: entpb.CreateBranchRequest
	(*GetBranchRequest)(nil),             // 6: entpb.GetBranchRequest
	(*UpdateBranchRequest)(nil),          // 7: entpb.UpdateBranchRequest
	(*DeleteBranchRequest)(nil),          // 8: entpb.DeleteBranchRequest
	(*ListBranchRequest)(nil),            // 9: entpb.ListBranchRequest
	(*ListBranchResponse)(nil),           // 10: entpb.ListBranchResponse
	(*BatchCreateBranchesRequest)(nil),   // 11: entpb.BatchCreateBranchesRequest
	(*BatchCreateBranchesResponse)(nil),  // 12: entpb.BatchCreateBranchesResponse
	(*Company)(nil),                      // 13: entpb.Company
	(*CreateCompanyRequest)(nil),         // 14: entpb.CreateCompanyRequest
	(*GetCompanyRequest)(nil),            // 15: entpb.GetCompanyRequest
	(*UpdateCompanyRequest)(nil),         // 16: entpb.UpdateCompanyRequest
	(*DeleteCompanyRequest)(nil),         // 17: entpb.DeleteCompanyRequest
	(*ListCompanyRequest)(nil),           // 18: entpb.ListCompanyRequest
	(*ListCompanyResponse)(nil),          // 19: entpb.ListCompanyResponse
	(*BatchCreateCompaniesRequest)(nil),  // 20: entpb.BatchCreateCompaniesRequest
	(*BatchCreateCompaniesResponse)(nil), // 21: entpb.BatchCreateCompaniesResponse
	(*timestamppb.Timestamp)(nil),        // 22: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 23: google.protobuf.Empty
}
var file_entpb_entpb_proto_depIdxs = []int32{
	22, // 0: entpb.Branch.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: entpb.Branch.updated_at:type_name -> google.protobuf.Timestamp
	13, // 2: entpb.Branch.company:type_name -> entpb.Company
	4,  // 3: entpb.CreateBranchRequest.branch:type_name -> entpb.Branch
	0,  // 4: entpb.GetBranchRequest.view:type_name -> entpb.GetBranchRequest.View
	4,  // 5: entpb.UpdateBranchRequest.branch:type_name -> entpb.Branch
	1,  // 6: entpb.ListBranchRequest.view:type_name -> entpb.ListBranchRequest.View
	4,  // 7: entpb.ListBranchResponse.branch_list:type_name -> entpb.Branch
	5,  // 8: entpb.BatchCreateBranchesRequest.requests:type_name -> entpb.CreateBranchRequest
	4,  // 9: entpb.BatchCreateBranchesResponse.branches:type_name -> entpb.Branch
	22, // 10: entpb.Company.created_at:type_name -> google.protobuf.Timestamp
	22, // 11: entpb.Company.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 12: entpb.Company.branches:type_name -> entpb.Branch
	13, // 13: entpb.CreateCompanyRequest.company:type_name -> entpb.Company
	2,  // 14: entpb.GetCompanyRequest.view:type_name -> entpb.GetCompanyRequest.View
	13, // 15: entpb.UpdateCompanyRequest.company:type_name -> entpb.Company
	3,  // 16: entpb.ListCompanyRequest.view:type_name -> entpb.ListCompanyRequest.View
	13, // 17: entpb.ListCompanyResponse.company_list:type_name -> entpb.Company
	14, // 18: entpb.BatchCreateCompaniesRequest.requests:type_name -> entpb.CreateCompanyRequest
	13, // 19: entpb.BatchCreateCompaniesResponse.companies:type_name -> entpb.Company
	5,  // 20: entpb.BranchService.Create:input_type -> entpb.CreateBranchRequest
	6,  // 21: entpb.BranchService.Get:input_type -> entpb.GetBranchRequest
	7,  // 22: entpb.BranchService.Update:input_type -> entpb.UpdateBranchRequest
	8,  // 23: entpb.BranchService.Delete:input_type -> entpb.DeleteBranchRequest
	9,  // 24: entpb.BranchService.List:input_type -> entpb.ListBranchRequest
	11, // 25: entpb.BranchService.BatchCreate:input_type -> entpb.BatchCreateBranchesRequest
	14, // 26: entpb.CompanyService.Create:input_type -> entpb.CreateCompanyRequest
	15, // 27: entpb.CompanyService.Get:input_type -> entpb.GetCompanyRequest
	16, // 28: entpb.CompanyService.Update:input_type -> entpb.UpdateCompanyRequest
	17, // 29: entpb.CompanyService.Delete:input_type -> entpb.DeleteCompanyRequest
	18, // 30: entpb.CompanyService.List:input_type -> entpb.ListCompanyRequest
	20, // 31: entpb.CompanyService.BatchCreate:input_type -> entpb.BatchCreateCompaniesRequest
	4,  // 32: entpb.BranchService.Create:output_type -> entpb.Branch
	4,  // 33: entpb.BranchService.Get:output_type -> entpb.Branch
	4,  // 34: entpb.BranchService.Update:output_type -> entpb.Branch
	23, // 35: entpb.BranchService.Delete:output_type -> google.protobuf.Empty
	10, // 36: entpb.BranchService.List:output_type -> entpb.ListBranchResponse
	12, // 37: entpb.BranchService.BatchCreate:output_type -> entpb.BatchCreateBranchesResponse
	13, // 38: entpb.CompanyService.Create:output_type -> entpb.Company
	13, // 39: entpb.CompanyService.Get:output_type -> entpb.Company
	13, // 40: entpb.CompanyService.Update:output_type -> entpb.Company
	23, // 41: entpb.CompanyService.Delete:output_type -> google.protobuf.Empty
	19, // 42: entpb.CompanyService.List:output_type -> entpb.ListCompanyResponse
	21, // 43: entpb.CompanyService.BatchCreate:output_type -> entpb.BatchCreateCompaniesResponse
	32, // [32:44] is the sub-list for method output_type
	20, // [20:32] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_entpb_entpb_proto_init() }
func file_entpb_entpb_proto_init() {
	if File_entpb_entpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entpb_entpb_proto_rawDesc), len(file_entpb_entpb_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_entpb_entpb_proto_goTypes,
		DependencyIndexes: file_entpb_entpb_proto_depIdxs,
		EnumInfos:         file_entpb_entpb_proto_enumTypes,
		MessageInfos:      file_entpb_entpb_proto_msgTypes,
	}.Build()
	File_entpb_entpb_proto = out.File
	file_entpb_entpb_proto_goTypes = nil
	file_entpb_entpb_proto_depIdxs = nil
}
