// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/hr.proto

package generate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCompanyRequest) Reset() {
	*x = ValidateCompanyRequest{}
	mi := &file_proto_hr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCompanyRequest) ProtoMessage() {}

func (x *ValidateCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCompanyRequest.ProtoReflect.Descriptor instead.
func (*ValidateCompanyRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateCompanyRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type ValidateCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCompanyResponse) Reset() {
	*x = ValidateCompanyResponse{}
	mi := &file_proto_hr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCompanyResponse) ProtoMessage() {}

func (x *ValidateCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCompanyResponse.ProtoReflect.Descriptor instead.
func (*ValidateCompanyResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateCompanyResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ValidateCompanyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_hr_proto protoreflect.FileDescriptor

const file_proto_hr_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/hr.proto\x12\x02hr\"7\n" +
	"\x16ValidateCompanyRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\"G\n" +
	"\x17ValidateCompanyResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2d\n" +
	"\x16ValidateCompanyService\x12J\n" +
	"\x0fValidateCompany\x12\x1a.hr.ValidateCompanyRequest\x1a\x1b.hr.ValidateCompanyResponseB\fZ\n" +
	"./generateb\x06proto3"

var (
	file_proto_hr_proto_rawDescOnce sync.Once
	file_proto_hr_proto_rawDescData []byte
)

func file_proto_hr_proto_rawDescGZIP() []byte {
	file_proto_hr_proto_rawDescOnce.Do(func() {
		file_proto_hr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hr_proto_rawDesc), len(file_proto_hr_proto_rawDesc)))
	})
	return file_proto_hr_proto_rawDescData
}

var file_proto_hr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_hr_proto_goTypes = []any{
	(*ValidateCompanyRequest)(nil),  // 0: hr.ValidateCompanyRequest
	(*ValidateCompanyResponse)(nil), // 1: hr.ValidateCompanyResponse
}
var file_proto_hr_proto_depIdxs = []int32{
	0, // 0: hr.ValidateCompanyService.ValidateCompany:input_type -> hr.ValidateCompanyRequest
	1, // 1: hr.ValidateCompanyService.ValidateCompany:output_type -> hr.ValidateCompanyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_hr_proto_init() }
func file_proto_hr_proto_init() {
	if File_proto_hr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hr_proto_rawDesc), len(file_proto_hr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hr_proto_goTypes,
		DependencyIndexes: file_proto_hr_proto_depIdxs,
		MessageInfos:      file_proto_hr_proto_msgTypes,
	}.Build()
	File_proto_hr_proto = out.File
	file_proto_hr_proto_goTypes = nil
	file_proto_hr_proto_depIdxs = nil
}
