// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/hr.proto

package generate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ValidateCompanyService_ValidateCompany_FullMethodName = "/hr.ValidateCompanyService/ValidateCompany"
)

// ValidateCompanyServiceClient is the client API for ValidateCompanyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidateCompanyServiceClient interface {
	ValidateCompany(ctx context.Context, in *ValidateCompanyRequest, opts ...grpc.CallOption) (*ValidateCompanyResponse, error)
}

type validateCompanyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValidateCompanyServiceClient(cc grpc.ClientConnInterface) ValidateCompanyServiceClient {
	return &validateCompanyServiceClient{cc}
}

func (c *validateCompanyServiceClient) ValidateCompany(ctx context.Context, in *ValidateCompanyRequest, opts ...grpc.CallOption) (*ValidateCompanyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCompanyResponse)
	err := c.cc.Invoke(ctx, ValidateCompanyService_ValidateCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidateCompanyServiceServer is the server API for ValidateCompanyService service.
// All implementations must embed UnimplementedValidateCompanyServiceServer
// for forward compatibility.
type ValidateCompanyServiceServer interface {
	ValidateCompany(context.Context, *ValidateCompanyRequest) (*ValidateCompanyResponse, error)
	mustEmbedUnimplementedValidateCompanyServiceServer()
}

// UnimplementedValidateCompanyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValidateCompanyServiceServer struct{}

func (UnimplementedValidateCompanyServiceServer) ValidateCompany(context.Context, *ValidateCompanyRequest) (*ValidateCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateCompany not implemented")
}
func (UnimplementedValidateCompanyServiceServer) mustEmbedUnimplementedValidateCompanyServiceServer() {
}
func (UnimplementedValidateCompanyServiceServer) testEmbeddedByValue() {}

// UnsafeValidateCompanyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidateCompanyServiceServer will
// result in compilation errors.
type UnsafeValidateCompanyServiceServer interface {
	mustEmbedUnimplementedValidateCompanyServiceServer()
}

func RegisterValidateCompanyServiceServer(s grpc.ServiceRegistrar, srv ValidateCompanyServiceServer) {
	// If the following call pancis, it indicates UnimplementedValidateCompanyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ValidateCompanyService_ServiceDesc, srv)
}

func _ValidateCompanyService_ValidateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidateCompanyServiceServer).ValidateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidateCompanyService_ValidateCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidateCompanyServiceServer).ValidateCompany(ctx, req.(*ValidateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValidateCompanyService_ServiceDesc is the grpc.ServiceDesc for ValidateCompanyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidateCompanyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hr.ValidateCompanyService",
	HandlerType: (*ValidateCompanyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateCompany",
			Handler:    _ValidateCompanyService_ValidateCompany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hr.proto",
}
