// Code generated by ent, DO NOT EDIT.

package ent

import (
	"hrm/ent/branch"
	"hrm/ent/company"
	"hrm/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	branchFields := schema.Branch{}.Fields()
	_ = branchFields
	// branchDescName is the schema descriptor for name field.
	branchDescName := branchFields[1].Descriptor()
	// branch.NameValidator is a validator for the "name" field. It is called by the builders before save.
	branch.NameValidator = branchDescName.Validators[0].(func(string) error)
	// branchDescCode is the schema descriptor for code field.
	branchDescCode := branchFields[2].Descriptor()
	// branch.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	branch.CodeValidator = branchDescCode.Validators[0].(func(string) error)
	// branchDescAddress is the schema descriptor for address field.
	branchDescAddress := branchFields[3].Descriptor()
	// branch.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	branch.AddressValidator = branchDescAddress.Validators[0].(func(string) error)
	// branchDescContactInfo is the schema descriptor for contact_info field.
	branchDescContactInfo := branchFields[4].Descriptor()
	// branch.ContactInfoValidator is a validator for the "contact_info" field. It is called by the builders before save.
	branch.ContactInfoValidator = branchDescContactInfo.Validators[0].(func(string) error)
	// branchDescCreatedAt is the schema descriptor for created_at field.
	branchDescCreatedAt := branchFields[5].Descriptor()
	// branch.DefaultCreatedAt holds the default value on creation for the created_at field.
	branch.DefaultCreatedAt = branchDescCreatedAt.Default.(func() time.Time)
	// branchDescUpdatedAt is the schema descriptor for updated_at field.
	branchDescUpdatedAt := branchFields[6].Descriptor()
	// branch.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	branch.DefaultUpdatedAt = branchDescUpdatedAt.Default.(func() time.Time)
	// branch.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	branch.UpdateDefaultUpdatedAt = branchDescUpdatedAt.UpdateDefault.(func() time.Time)
	// branchDescID is the schema descriptor for id field.
	branchDescID := branchFields[0].Descriptor()
	// branch.DefaultID holds the default value on creation for the id field.
	branch.DefaultID = branchDescID.Default.(func() uuid.UUID)
	companyFields := schema.Company{}.Fields()
	_ = companyFields
	// companyDescName is the schema descriptor for name field.
	companyDescName := companyFields[1].Descriptor()
	// company.NameValidator is a validator for the "name" field. It is called by the builders before save.
	company.NameValidator = companyDescName.Validators[0].(func(string) error)
	// companyDescAddress is the schema descriptor for address field.
	companyDescAddress := companyFields[2].Descriptor()
	// company.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	company.AddressValidator = companyDescAddress.Validators[0].(func(string) error)
	// companyDescCreatedAt is the schema descriptor for created_at field.
	companyDescCreatedAt := companyFields[3].Descriptor()
	// company.DefaultCreatedAt holds the default value on creation for the created_at field.
	company.DefaultCreatedAt = companyDescCreatedAt.Default.(func() time.Time)
	// companyDescUpdatedAt is the schema descriptor for updated_at field.
	companyDescUpdatedAt := companyFields[4].Descriptor()
	// company.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	company.DefaultUpdatedAt = companyDescUpdatedAt.Default.(func() time.Time)
	// company.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	company.UpdateDefaultUpdatedAt = companyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// companyDescID is the schema descriptor for id field.
	companyDescID := companyFields[0].Descriptor()
	// company.DefaultID holds the default value on creation for the id field.
	company.DefaultID = companyDescID.Default.(func() uuid.UUID)
}
