// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Branch is the predicate function for branch builders.
type Branch func(*sql.Selector)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)
